### ISSUE TITLE
ImportError: cannot import name 'SemiParametricRegressionFittter' from 'lifelines.fitters' 

### ISSUE THREAD

**Issue by vishnuswaroop21** [d909b/CovEWS#1]
I was trying to black box dry run the code to see what to expect, facing an issue regarding import function, can you tell me how to solve it.

Traceback (most recent call last):
  File "/home/vishnu/try/covews/apps/main.py", line 399, in <module>
    app.run()
  File "/home/vishnu/anaconda3/envs/kaggle/lib/python3.8/site-packages/covews/apps/base_application.py", line 141, in run
    return self.run_single(evaluate_against=evaluate_against)
  File "/home/vishnu/anaconda3/envs/kaggle/lib/python3.8/site-packages/covews/apps/base_application.py", line 156, in run_single
    model, history = self.train_model(train_generator,
  File "/home/vishnu/anaconda3/envs/kaggle/lib/python3.8/site-packages/covews/apps/util.py", line 87, in func_wrapper
    return_value = func(*args, **kargs)
  File "/home/vishnu/try/covews/apps/main.py", line 237, in train_model
    best_model_path = self.get_best_model_path()
  File "/home/vishnu/try/covews/apps/main.py", line 155, in get_best_model_path
    model_class = self.get_model_type_for_method_name()
  File "/home/vishnu/try/covews/apps/main.py", line 211, in get_model_type_for_method_name
    mod = importlib.import_module(fully_qualified_name)
  File "/home/vishnu/anaconda3/envs/kaggle/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/vishnu/anaconda3/envs/kaggle/lib/python3.8/site-packages/covews/models/baselines/time_varying_cox.py", line 24, in <module>
    from covews.models.nonlinear_cox.cox_time_varying_fitter import CoxTimeVaryingFitter
  File "/home/vishnu/anaconda3/envs/kaggle/lib/python3.8/site-packages/covews/models/nonlinear_cox/cox_time_varying_fitter.py", line 57, in <module>
    from lifelines.fitters import SemiParametricRegressionFittter
ImportError: cannot import name 'SemiParametricRegressionFittter' from 'lifelines.fitters' (/home/vishnu/anaconda3/envs/kaggle/lib/python3.8/site-packages/lifelines/fitters/__init__.py)

**Comment by d909b** [comment]
@vishnuswaroop21  Thank you. Looks like `lifelines` changed the name of the imported class from `SemiParametricRegressionFittter` to `SemiParametricRegressionFitter` after version 0.24.8.

I pinned lifelines to 0.24.8 in `setup.py` in the master latest commit. Please pull and reinstall and the problem should be resolved.

Many thanks.
